monolog:
    handlers:
        console:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%-console.log"
            level: error
            channels: ["console"]
            max_files: 10
        mail:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%-mail.log"
            level: error
            channels: ["mail"]
            max_files: 10
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!event","!console","!mail"]
            max_files: 10
            formatter: monolog.formatter.user_request