twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: false
    exception_controller: null
    paths:
        'public/images': images
        'public/css': styles
