<?php

namespace App\DBAL;

class RoleNameEnum extends EnumType
{
    protected $name = self::class;
    protected $values = ['ROLE_CLIENT','ROLE_ADMIN','ROLE_SUPER_ADMIN','ROLE_FORMATION_READ','ROLE_FORMATION_CREATE','ROLE_FORMATION_DELETE','ROLE_SIGNATURE_READ','ROLE_SIGNATURE_CREATE','ROLE_SIGNATURE_DELETE','ROLE_SIGNATUREPACK_CREATE','ROLE_DOCUMENT_READ','ROLE_NEWS_READ'];
}